In [70]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

small =  {0: [2, 8],
 1: [2, 3, 5, 6, 7, 9],
 2: [0, 1, 3, 4, 5, 9],
 3: [1, 2, 4, 7, 8],
 4: [2, 3, 6],
 5: [1, 2],
 6: [1, 4],
 7: [1, 3],
 8: [0, 3],
 9: [1, 2]}

G = nx.from_dict_of_lists(small)

creditw_truth = np.random.random(10) > 0.5
print(creditw_truth)


p_true_posit = 0.90
p_false_posit = 0.1
std_dev = 0.05


G_adj = nx.to_numpy_matrix(G)
print(G_adj)
local_trust = np.array(G_adj.copy() )

for (x,y), element in np.ndenumerate(G_adj):
    if element:
        if creditw_truth[y]:
            rec = min(np.random.normal(p_true_posit, std_dev),1)
        else:
            rec = max(np.random.normal(p_false_posit, std_dev),0)
        local_trust[x][y] = rec
    # else, not connected
np.set_printoptions(precision=3)
print(local_trust)

local_trust = np.array(local_trust)
print(np.sum(local_trust, axis=1))
normalized_local_trust = (local_trust.T / np.sum(local_trust, axis=1)).T
print(normalized_local_trust)

[False  True False False False  True  True False  True False]
[[0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 1. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 1. 0. 0. 0. 1.]
 [0. 1. 1. 0. 1. 0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]]
[[0.    0.    0.214 0.    0.    0.    0.    0.    0.865 0.   ]
 [0.    0.    0.093 0.195 0.    0.914 0.866 0.066 0.    0.012]
 [0.149 0.971 0.    0.091 0.004 1.    0.    0.    0.    0.082]
 [0.    0.816 0.177 0.    0.143 0.    0.    0.215 0.929 0.   ]
 [0.    0.    0.096 0.02  0.    0.    0.877 0.    0.    0.   ]
 [0.    0.94  0.134 0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.803 0.    0.    0.119 0.    0.    0.    0.    0.   ]
 [0.    0.872 0.    0.089 0.    0.    0.    0.    0.    0.   ]
 [0.113 0.    0.    0.087 0.    0.    0.    0.    0.    0.   ]
 [0.    0.885 0.129 0.    0.    0.    0.

In [75]:
e = np.average(normalized_local_trust, axis=0)
C = normalized_local_trust
print(e)

t = np.dot(C.T, e)
print('t')

scores = t.copy()
for i in range(10):
    new_scores = np.dot(C.T, scores)
    p
    dist = new_scores - scores
    scores = new_scores


[0.063 0.431 0.067 0.068 0.019 0.086 0.129 0.013 0.121 0.004]
t
