In [84]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

small =  {0: [2, 8],
 1: [2, 3, 5, 6, 7, 9],
 2: [0, 1, 3, 4, 5, 9],
 3: [1, 2, 4, 7, 8],
 4: [2, 3, 6],
 5: [1, 2],
 6: [1, 4],
 7: [1, 3],
 8: [0, 3],
 9: [1, 2]}

G = nx.from_dict_of_lists(small)

creditw_truth = np.random.random(10) < 0.5
print(creditw_truth)

p_true_posit = 0.90
p_false_posit = 0.1
std_dev = 0.05

G_adj = nx.to_numpy_matrix(G)
print(G_adj)
local_trust = np.array(G_adj.copy() )

for (x,y), element in np.ndenumerate(G_adj):
    if element:
        if creditw_truth[y]:
            rec = min(np.random.normal(p_true_posit, std_dev),1)
        else:
            rec = max(np.random.normal(p_false_posit, std_dev),0)
        local_trust[x][y] = rec
    # else, not connected
np.set_printoptions(precision=3)
print(local_trust)

local_trust = np.array(local_trust)
print(np.sum(local_trust, axis=1))
normalized_local_trust = (local_trust.T / np.sum(local_trust, axis=1)).T
print(normalized_local_trust)

[False  True False  True False  True  True  True  True  True]
[[0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 1. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 1. 0. 0. 0. 1.]
 [0. 1. 1. 0. 1. 0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]]
[[0.    0.    0.041 0.    0.    0.    0.    0.    0.918 0.   ]
 [0.    0.    0.029 0.934 0.    0.872 0.855 0.911 0.    0.865]
 [0.088 0.932 0.    0.807 0.106 0.914 0.    0.    0.    0.974]
 [0.    0.872 0.153 0.    0.079 0.    0.    0.893 0.911 0.   ]
 [0.    0.    0.206 0.948 0.    0.    0.833 0.    0.    0.   ]
 [0.    0.992 0.042 0.    0.    0.    0.    0.    0.    0.   ]
 [0.    0.914 0.    0.    0.038 0.    0.    0.    0.    0.   ]
 [0.    0.908 0.    0.972 0.    0.    0.    0.    0.    0.   ]
 [0.108 0.    0.    0.954 0.    0.    0.    0.    0.    0.   ]
 [0.    0.866 0.123 0.    0.    0.    0.

In [85]:
e = np.average(normalized_local_trust, axis=0)
C = normalized_local_trust
print(e)

t = np.dot(C.T, e)
print('t')

scores = t.copy()
for i in range(100):
    new_scores = np.dot(C.T, scores)
    dist = np.linalg.norm(new_scores - scores)
    scores = new_scores
    print(dist)
    print(scores)
    print('\n')


[0.012 0.382 0.037 0.231 0.009 0.043 0.061 0.051 0.127 0.045]
t
0.1457472748983038
[0.009 0.375 0.029 0.213 0.01  0.053 0.051 0.121 0.086 0.053]


0.11334808845719972
[0.009 0.275 0.024 0.229 0.009 0.08  0.076 0.142 0.075 0.08 ]


0.09839454380095228
[0.008 0.363 0.028 0.208 0.01  0.059 0.056 0.127 0.081 0.059]


0.07925456236320448
[0.009 0.294 0.024 0.225 0.009 0.078 0.074 0.138 0.073 0.078]


0.06768448778784293
[0.008 0.353 0.028 0.208 0.01  0.063 0.06  0.129 0.079 0.063]


0.055686951754815237
[0.009 0.305 0.025 0.222 0.009 0.076 0.072 0.136 0.073 0.075]


0.04713851638051269
[0.008 0.346 0.027 0.209 0.01  0.065 0.062 0.13  0.078 0.065]


0.03920740877136005
[0.009 0.312 0.025 0.22  0.009 0.074 0.07  0.135 0.073 0.074]


0.03305793445201584
[0.008 0.34  0.027 0.21  0.009 0.067 0.063 0.131 0.077 0.067]


0.027647201278655106
[0.008 0.317 0.026 0.218 0.009 0.073 0.069 0.134 0.073 0.073]


0.023272924422377644
[0.008 0.336 0.027 0.211 0.009 0.068 0.064 0.132 0.076 0.068]


0.01951812