In [87]:
import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

small =  {0: [2, 8],
 1: [2, 3, 5, 6, 7, 9],
 2: [0, 1, 3, 4, 5, 9],
 3: [1, 2, 4, 7, 8],
 4: [2, 3, 6],
 5: [1, 2],
 6: [1, 4],
 7: [1, 3],
 8: [0, 3],
 9: [1, 2]}

G = nx.from_dict_of_lists(small)

creditw_truth = np.random.random(10) > 0.5
print(creditw_truth)


p_true_posit = 0.90
p_false_posit = 0.1
std_dev = 0.05


local_trust = {}
for i in range(len(small)):
    local_trust[i] = []
    
for nodeA, nodeBs in small.items():
    for nodeB in nodeBs:
        if creditw_truth[nodeB]:
            # high likelihood
            #rec = np.random.random() < p_true_posit
            rec = min(np.random.normal(p_true_posit, std_dev),1)
        else:
            # small likelihood false positive
            #rec = np.random.random() > p_true_posit
            #rec = np.random.random() * p_true_posit
            rec = max(np.random.normal(p_false_posit, std_dev),0)
        local_trust[nodeA].append(rec)
        
for foo in local_trust:
    print(foo, [round(z, 2) for z in local_trust[foo]])
    
normalized_local_trust = {}
for i in range(len(small)):
    normalized_local_trust[i] = np.array([])
    
for nodeA, trustB in local_trust.items():
    trust = np.array(trustB)
    trust /= trust.sum()
    normalized_local_trust[nodeA] = trust

for nodeA, vals in small.items():
    for i, val in enumerate(vals):
        G[nodeA][val]['weight'] = normalized_local_trust[nodeA][i]

plt.figure(num=None, figsize=(8, 6), dpi=80, facecolor='w', edgecolor='k')

#nx.draw(G, with_labels=True, node_size=700)
#plt.show()

G2 = nx.from_dict_of_lists(normalized_local_trust)
A = nx.adj_matrix(G)
print(G.edges(data=True))
#print(A.todense())
#print(nx.to_dict_of_dicts(G))

[ True False  True  True  True False  True  True False  True]
0 [0.95, 0.15]
1 [0.98, 0.9, 0.09, 0.93, 0.87, 0.89]
2 [0.89, 0.1, 0.91, 0.9, 0.09, 0.95]
3 [0.08, 0.91, 0.91, 0.92, 0.05]
4 [0.87, 0.87, 0.94]
5 [0.17, 0.93]
6 [0.18, 0.93]
7 [0.09, 0.85]
8 [0.98, 0.92]
9 [0.1, 0.92]
[(0, 2, {'weight': 0.231285628154948}), (0, 8, {'weight': 0.515571218773627}), (1, 2, {'weight': 0.026801890171861534}), (1, 3, {'weight': 0.028408027441089483}), (1, 5, {'weight': 0.15101837821443495}), (1, 6, {'weight': 0.16383407975089706}), (1, 7, {'weight': 0.1004281477985002}), (1, 9, {'weight': 0.10209550559152947}), (2, 3, {'weight': 0.31722965496805616}), (2, 4, {'weight': 0.3238533929119369}), (2, 5, {'weight': 0.8489816217855649}), (2, 9, {'weight': 0.8979044944084704}), (3, 4, {'weight': 0.32569671167287056}), (3, 7, {'weight': 0.8995718522014998}), (3, 8, {'weight': 0.484428781226373}), (4, 6, {'weight': 0.8361659202491029})]


<Figure size 640x480 with 0 Axes>

In [86]:
# now mess with it so that the matrix is not symmetric... so let that be our baseline creditworthiness scores, but we also need our f

In [84]:
# basically we have a creditw truth vector for each node
np.set_printoptions(precision=3)
weighted_adj = nx.to_numpy_matrix(G, weight='weight')
print(weighted_adj)

[[0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 1. 1. 0. 1. 1. 1. 0. 1.]
 [1. 1. 0. 1. 1. 1. 0. 0. 0. 1.]
 [0. 1. 1. 0. 1. 0. 0. 1. 1. 0.]
 [0. 0. 1. 1. 0. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]]


In [79]:
e = np.average(weighted_adj, axis=0)
print(e)
t = e
for i in range(10):
    t = 

[[0.008 0.323 0.224 0.263 0.077 0.1   0.1   0.1   0.1   0.1  ]]
